#!/bin/bash
set -e

APP_DIR="/opt/tg-broadcast-bot"
SERVICE_NAME="tg-broadcast"

echo "===== Deploy start ====="
cd $APP_DIR

# Подтягиваем изменения
git fetch origin main
git reset --hard origin/main

# Устанавливаем зависимости (на всякий случай)
pip3 install -r requirements.txt --upgrade

# Перезапускаем systemd сервис
systemctl daemon-reload
systemctl restart $SERVICE_NAME

echo "===== Deploy finished ====="
systemctl status $SERVICE_NAME --no-pager -l
