name: Deploy bot to server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: BOT_TOKEN,ADMIN_IDS,DEFAULT_TTL_MIN
          script_stop: true
          timeout: 15m
          command_timeout: 12m
          script: |
            set -euxo pipefail
            echo "[run] deploy.sh"
            bash /opt/tg-broadcast/deploy.sh
            systemctl daemon-reload || true
            systemctl restart tg-broadcast.service || true
            echo "[status]"
            systemctl status tg-broadcast.service --no-pager || true
            echo "[logs]"
            journalctl -u tg-broadcast.service -n 120 --no-pager || true
